
	 
	/*
	 *	This content is generated from the API File Info.
	 *	(Alt+Shift+Ctrl+I).
	 *
	 *	@desc 		
	 *	@file 		iphone_14_plus___1
	 *	@date 		Thursday 04th of May 2023 03:33:10 AM
	 *	@title 		Page 1
	 *	@author 	
	 *	@keywords 	
	 *	@generator 	Export Kit v1.3.figma
	 *
	 */
	

package com.cindy.tammodulone;

import android.app.Activity;
import android.os.Bundle;


import android.view.View;
import android.widget.TextView;
import android.widget.ImageView;

public class iphone_14_plus___1_activity extends Activity {

	
	private View _bg__iphone_14_plus___1_ek2;
	private View rectangle_29;
	private TextView jenis_jenis_pelecehan_seksual_menurut_kategorinya__pelecehan_seksual_dibagi_menjadi_5_jenis__yaitu__pelecehan_gender___pernyataan_dan_perilaku_seksis_yang_menghina_atau_merendahkan_wanita__contohnya_termasuk_komentar_yang_menghina__gambar_atau_tulisan_yang_merendahkan_wanita__lelucon_cabul_atau_humor_tentang_seks_atau_wanita_pada_umumnya__perilaku_menggoda___perilaku_seksual_yang_menyinggung__tidak_pantas__dan_tidak_diinginkan__contohnya_termasuk_mengulangi_ajakan_seksual_yang_tidak_diinginkan__memaksa_untuk_makan_malam__minum__atau_kencan__mengirimkan_surat_dan_panggilan_telepon_yang_tak_henti_henti_meski_sudah_ditolak__serta_ajakan_lainnya__penyuapan_seksual___permintaan_aktivitas_seksual_atau_perilaku_terkait_seks_lainnya_dengan_janji_imbalan__rencana_mungkin_dilakukan_secara_terang_terangan_atau_secara_halus__pemaksaan_seksual___pemaksaan_aktivitas_seksual_atau_perilaku_terkait_seks_lainnya_dengan_ancaman_hukuman__contohnya_seperti_evaluasi_kerja_yang_negatif__pencabutan_promosi_kerja__dan_ancaman_pembunuhan_;
	private TextView mengenali_jenis_pelecehan_seksual;
	private ImageView gender_violence_pana_1;
	private TextView information_module;
	private ImageView icons8_before_playlist_button_on_a_music_application_48__4__2;
	private ImageView icons8_close_window_48_2;

	@Override
	public void onCreate(Bundle savedInstanceState) {

		super.onCreate(savedInstanceState);
		setContentView(R.layout.iphone_14_plus___1);

		
		_bg__iphone_14_plus___1_ek2 = (View) findViewById(R.id._bg__iphone_14_plus___1_ek2);
		rectangle_29 = (View) findViewById(R.id.rectangle_29);
		jenis_jenis_pelecehan_seksual_menurut_kategorinya__pelecehan_seksual_dibagi_menjadi_5_jenis__yaitu__pelecehan_gender___pernyataan_dan_perilaku_seksis_yang_menghina_atau_merendahkan_wanita__contohnya_termasuk_komentar_yang_menghina__gambar_atau_tulisan_yang_merendahkan_wanita__lelucon_cabul_atau_humor_tentang_seks_atau_wanita_pada_umumnya__perilaku_menggoda___perilaku_seksual_yang_menyinggung__tidak_pantas__dan_tidak_diinginkan__contohnya_termasuk_mengulangi_ajakan_seksual_yang_tidak_diinginkan__memaksa_untuk_makan_malam__minum__atau_kencan__mengirimkan_surat_dan_panggilan_telepon_yang_tak_henti_henti_meski_sudah_ditolak__serta_ajakan_lainnya__penyuapan_seksual___permintaan_aktivitas_seksual_atau_perilaku_terkait_seks_lainnya_dengan_janji_imbalan__rencana_mungkin_dilakukan_secara_terang_terangan_atau_secara_halus__pemaksaan_seksual___pemaksaan_aktivitas_seksual_atau_perilaku_terkait_seks_lainnya_dengan_ancaman_hukuman__contohnya_seperti_evaluasi_kerja_yang_negatif__pencabutan_promosi_kerja__dan_ancaman_pembunuhan_ = (TextView) findViewById(R.id.jenis_jenis_pelecehan_seksual_menurut_kategorinya__pelecehan_seksual_dibagi_menjadi_5_jenis__yaitu__pelecehan_gender___pernyataan_dan_perilaku_seksis_yang_menghina_atau_merendahkan_wanita__contohnya_termasuk_komentar_yang_menghina__gambar_atau_tulisan_yang_merendahkan_wanita__lelucon_cabul_atau_humor_tentang_seks_atau_wanita_pada_umumnya__perilaku_menggoda___perilaku_seksual_yang_menyinggung__tidak_pantas__dan_tidak_diinginkan__contohnya_termasuk_mengulangi_ajakan_seksual_yang_tidak_diinginkan__memaksa_untuk_makan_malam__minum__atau_kencan__mengirimkan_surat_dan_panggilan_telepon_yang_tak_henti_henti_meski_sudah_ditolak__serta_ajakan_lainnya__penyuapan_seksual___permintaan_aktivitas_seksual_atau_perilaku_terkait_seks_lainnya_dengan_janji_imbalan__rencana_mungkin_dilakukan_secara_terang_terangan_atau_secara_halus__pemaksaan_seksual___pemaksaan_aktivitas_seksual_atau_perilaku_terkait_seks_lainnya_dengan_ancaman_hukuman__contohnya_seperti_evaluasi_kerja_yang_negatif__pencabutan_promosi_kerja__dan_ancaman_pembunuhan_);
		mengenali_jenis_pelecehan_seksual = (TextView) findViewById(R.id.mengenali_jenis_pelecehan_seksual);
		gender_violence_pana_1 = (ImageView) findViewById(R.id.gender_violence_pana_1);
		information_module = (TextView) findViewById(R.id.information_module);
		icons8_before_playlist_button_on_a_music_application_48__4__2 = (ImageView) findViewById(R.id.icons8_before_playlist_button_on_a_music_application_48__4__2);
		icons8_close_window_48_2 = (ImageView) findViewById(R.id.icons8_close_window_48_2);
	
		
		//custom code goes here
	
	}
}
	
	